package jp.ne.hatena.hackugyo.procon.model;

import com.j256.ormlite.field.DatabaseField;

import jp.ne.hatena.hackugyo.procon.util.StringUtils;

/**
 * 引用元
 */
public class CitationResource {
    // we use this field-name so we can query for users with a certain id
    public final static String ID_FIELD_NAME = "id";
    public final static String NAME_FIELD_NAME = "name";

    // this id is generated by the database and set on the object when it is passed to the create method
    @DatabaseField(generatedId = true, columnName = ID_FIELD_NAME)
    long id;

    @DatabaseField(columnName = NAME_FIELD_NAME)
    String name;



    CitationResource() {
        // for ormlite
    }

    public CitationResource(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }


    @Override
    public String toString() {
        String s = super.toString();
        return StringUtils.build(s, "{",
                "id: ", StringUtils.valueOf(id),
                ", name: ", name,
                "}"
        );
    }
}
