package jp.ne.hatena.hackugyo.procon.model;

import com.j256.ormlite.field.DatabaseField;

/**
 * 引用元
 */
public class CitationResource {
    // we use this field-name so we can query for users with a certain id
    public final static String ID_FIELD_NAME = "id";

    // this id is generated by the database and set on the object when it is passed to the create method
    @DatabaseField(generatedId = true, columnName = ID_FIELD_NAME)
    int id;

    @DatabaseField
    String name;



    CitationResource() {
        // for ormlite
    }

    public CitationResource(String name) {
        this.name = name;
    }
}
